AllCops:
  # All style checks are off by default, must be manually enabled
  DisabledByDefault: true

  # Include common Ruby source files.
  Include:
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
  Exclude:
    - 'vendor/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'app/views/forem'

Style/AccessModifierIndentation:
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent

Style/AlignArray:
  Enabled: true

Style/AlignHash:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/ClassAndModuleCamelCase:
  Enabled: true

Style/ConstantName:
  Enabled: true

Style/DeprecatedHashMethods:
  Enabled: true

Style/ElseAlignment:
  Enabled: true

Style/EmptyLineBetweenDefs:
  Enabled: true

Style/EmptyLines:
  Enabled: true

Style/EndOfLine:
  Enabled: true

Style/ExtraSpacing:
  Enabled: true

Style/FileName:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  Enabled: true
  Exclude:
    - 'config/routes.rb'

Style/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Style/IndentationWidth:
  Enabled: true
  Width: 2

Style/MethodName:
  Enabled: true
  EnforcedStyle: snake_case

Style/NilComparison:
  Enabled: true

Style/RescueEnsureAlignment:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true
  AllowIfMethodIsEmpty: true

Style/SpaceBeforeFirstArg:
  Enabled: true

Style/SpaceAfterColon:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAroundKeyword:
  Enabled: true

Style/SpaceAfterMethodName:
  Enabled: true

Style/SpaceAfterSemicolon:
  Enabled: true

Style/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space

Style/SpaceBeforeComma:
  Enabled: true

Style/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Style/SpaceAroundOperators:
  Enabled: true

Style/Tab:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true
  EnforcedStyle: final_newline

Style/TrailingWhitespace:
  Enabled: true

Style/VariableName:
  Enabled: true
  EnforcedStyle: snake_case

Lint/Debugger:
  Enabled: true


# Allow safe assignment in conditions.
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicatedKey:
  Enabled: true

Lint/Eval:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true
