script:
- 'export PULL_REQUEST_ID=${TRAVIS_PULL_REQUEST} &&
   export GITHUB_ACCESS_TOKEN=c80ee3816e08808f1af3bc115d0e79a917ca1ca7 &&
   bundle exec pronto run -f github_pr'
- 'RAILS_ENV=test bundle exec rake db:setup && RAILS_ENV=test bundle exec rake spec'
sudo: false
cache: bundler
